### ISSUE TITLE
Stored procedure result set type is not generated

### ISSUE THREAD

**Issue by IvanFarkas** [ClayLipscomb/Odapter#2]
# Stored procedure result set type is not generated

Great code!
It would be even better if it generates the T_pItemsListUntyped result set type.
Have I missed something?
How would I do that?

```csharp
public void GetItem<T_pItemsListUntyped>(String pItemnumber, String pItemcateory, out IList<T_pItemsListUntyped> pItemsList, out String pStatus,  
  bool mapColumnToObjectPropertyByPosition = false, bool allowUnmappedColumnsToBeExcluded = false, UInt32? optionalMaxNumberRowsToReadFromAnyCursor = null, OracleConnection optionalPreexistingOpenConnection = null)
  where T_pItemsListUntyped : class, new() {}
```

**Comment by ClayLipscomb** [comment]
It should generate it only if the respective cursor is defined using a record type (statically typed).  Otherwise, a C# DTO must be manually built based on the expected type of the result set, and a mapping strategy must be used to hydrate. The example code in the readme contains these scenarios. If you are using a Filter Prefix and the record type is defined external to the package you are generating, make sure you check Duplicate Referenced Record Types Outside Filter Prefix.
